name: Specs & Lint
on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v2
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
      - name: Install shards
        run: shards install
      - name: Run tests
        run: make test_all
      - name: Build
        run: make debug
      - name: Check formatting
        run: crystal tool format; git diff --exit-code