name: Release

on: 
  workflow_dispatch:
    inputs:
      latest:
        description: 'Tag the published docker image as the "latest"'
        required: false
        type: boolean
        default: false

jobs:
  build_linux_static:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:latest-alpine
    outputs:
      version: ${{ steps.version.outputs.VERSION }}
    steps:
      - name: Download source
        uses: actions/checkout@v2
      - name: Retrieve version
        run: |
          echo "VERSION=$(shards version)" >> "$GITHUB_OUTPUT"
        id: version
      - name: Build
        run: make static_mt
      - name: Make binary executable
        run: chmod +x bin/blahaj
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: blahaj-${{ steps.version.outputs.VERSION }}-linux-x86_64-static
          path: bin/blahaj

  release:
    runs-on: ubuntu-latest
    needs: build_linux_static
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: ./GH_ARTIFACTS
      - name: Make all binaries executable
        run: chmod +x GH_ARTIFACTS/**/*
      - name: Create zips
        run: cd GH_ARTIFACTS && find . -maxdepth 1 -mindepth 1 -type d -execdir zip -jr '{}.zip' '{}' \; && cd ..
      - uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            GH_ARTIFACTS/*.zip

  publish-docker:
    runs-on: ubuntu-latest
    needs: build_linux_static
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Container Metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/blahaj
          flavor: |
            latest=false
            prefix=
            suffix=
          tags: |
            type=raw,value=latest,enable=${{ inputs.latest }}
            type=raw,value=latest-unstable,enable={{is_default_branch}}
            type=raw,value=${{needs.build_linux_static.outputs.version}}
      - name: Build and Push Container
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64,linux/386,linux/arm64,linux/arm/v6,linux/arm/v7
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max